os:
# - linux
- osx
# - windows
dist: xenial
osx_image: xcode8
language: node_js
node_js:
- '10'
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_install:
- brew update && brew install git-lfs
- git lfs install
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      before_script:
        - git lfs pull
      script:
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    # - stage: Deploy linux
      # if: tag IS present
      # os: linux
      # dist: trusty
      # script:
      #   - npm run release
